"""Regenerate every committed data file for the dice-and-modifiers domain.

Run from anywhere: paths resolve relative to this file. Outputs land in ``../data``.
"""

from __future__ import annotations

from pathlib import Path

import dice
import tables

DATA = Path(__file__).resolve().parent.parent / "data"

NETS = range(-6, 7)  # advantage/disadvantage nets to tabulate


def _round(x: float) -> float:
    return round(x, 6)


def summary() -> dict:
    base = dice.roll_distribution()
    sums = list(base)
    return {
        "faces": dice.FACES,
        "keep": dice.KEEP,
        "base_min": min(sums),
        "base_max": max(sums),
        "base_mean": _round(dice.distribution_mean(base)),
        "base_stdev": _round(dice.distribution_stdev(base)),
    }


def roll_distributions() -> dict:
    out = {}
    for net in NETS:
        dist = dice.roll_distribution(av=max(net, 0), dv=max(-net, 0))
        cdf = dice.cdf_at_least(dist)
        out[str(net)] = {
            "mean": _round(dice.distribution_mean(dist)),
            "stdev": _round(dice.distribution_stdev(dist)),
            "pmf": {str(s): _round(float(p)) for s, p in dist.items()},
            "cdf_at_least": {str(s): _round(float(p)) for s, p in cdf.items()},
        }
    return out


def advantage_values() -> list[dict]:
    mid = 20  # the 50% target for a character adding no modifiers
    rows = []
    for net in NETS:
        av, dv = max(net, 0), max(-net, 0)
        dist = dice.roll_distribution(av, dv)
        rows.append(
            {
                "net": net,
                "dice_kept_of": dice.KEEP + abs(net),
                "mean_kept": _round(dice.distribution_mean(dist)),
                "p_meet_20": _round(float(dice.p_at_least(dist, mid))),
            }
        )
    return rows


def crit_rates() -> list[dict]:
    rows = []
    for net in NETS:
        av, dv = max(net, 0), max(-net, 0)
        cs = float(dice.crit_success(av, dv))
        cf = float(dice.crit_fail(av, dv))
        rows.append(
            {
                "net": net,
                "crit_success": _round(cs),
                "crit_success_one_in": round(1 / cs) if cs else None,
                "crit_fail": _round(cf),
                "crit_fail_one_in": round(1 / cf) if cf else None,
            }
        )
    return rows


def opposed_curve() -> list[dict]:
    rows = []
    for edge in range(0, 11):
        win, tie, lose = dice.opposed_outcome(mod_edge=edge)
        rows.append(
            {"edge": edge, "win": _round(win), "tie": _round(tie), "lose": _round(lose)}
        )
    return rows


def write_markdown() -> None:
    av_rows = [
        [
            tables.signed(r["net"]),
            r["dice_kept_of"],
            f"{r['mean_kept']:.2f}",
            tables.pct(r["p_meet_20"]),
        ]
        for r in advantage_values()
    ]
    tables.write_text(
        DATA / "advantage-values.md",
        markdown_intro("Value of net Advantage/Disadvantage (keep 3 of 3+|net| d12), and the"
                       " chance to meet a mid target of 20.")
        + tables.markdown_table(
            ["Net", "Dice kept of", "Mean kept sum", "Meet 20"], av_rows
        ),
    )

    def _one_in(n: int | None) -> str:
        return f"1 in {n:,}" if n else "never"

    crit_rows = [
        [
            tables.signed(r["net"]),
            tables.pct(r["crit_success"], 3),
            _one_in(r["crit_success_one_in"]),
            tables.pct(r["crit_fail"], 3),
            _one_in(r["crit_fail_one_in"]),
        ]
        for r in crit_rates()
    ]
    tables.write_text(
        DATA / "crit-rates.md",
        markdown_intro("Critical rates by net Advantage/Disadvantage.")
        + tables.markdown_table(
            ["Net", "Crit success", "", "Crit failure", ""], crit_rows
        ),
    )

    opp_rows = [
        [r["edge"], tables.pct(r["win"]), tables.pct(r["tie"]), tables.pct(r["lose"])]
        for r in opposed_curve()
    ]
    tables.write_text(
        DATA / "opposed.md",
        markdown_intro("Opposed rolls: chance the actor's dice strictly beat the opponent's,"
                       " by the actor's modifier edge (ties resolved by higher modifier).")
        + tables.markdown_table(["Modifier edge", "Win", "Tie", "Lose"], opp_rows),
    )


def markdown_intro(text: str) -> str:
    return f"<!-- generated by dice-and-modifiers/lab/generate.py -->\n\n{text}\n\n"


def main() -> None:
    tables.write_json(DATA / "summary.json", summary())
    tables.write_json(DATA / "roll-distributions.json", roll_distributions())
    tables.write_json(DATA / "advantage-values.json", advantage_values())
    tables.write_json(DATA / "crit-rates.json", crit_rates())
    tables.write_json(DATA / "opposed.json", opposed_curve())
    write_markdown()


if __name__ == "__main__":
    main()
