"""Regenerate the derived combat tables.

Reads the 3d12 keep-3 distributions from the dice-and-modifiers domain. The armour catalog is
authored in armor-class.md, so it is not read here; the lab works on values, not named armours.
Run from anywhere: paths resolve relative to this file.
"""

from __future__ import annotations

import json
from pathlib import Path

import combat

DATA = Path(__file__).resolve().parent.parent / "data"

SAMPLE_HP = 30  # placeholder until the Attunement HP curve exists


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _md_table(headers: list[str], rows: list[list[object]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = [f"| {' | '.join(str(c) for c in r)} |" for r in rows]
    return "\n".join([head, sep, *body]) + "\n"


def _write_json(path: Path, obj: object) -> None:
    path.write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8")


def _write_md(path: Path, intro: str, headers: list[str], rows: list[list[object]]) -> None:
    header = "<!-- generated by combat-system/lab/generate.py -->\n\n"
    path.write_text(header + intro + "\n\n" + _md_table(headers, rows), encoding="utf-8")


def hit_by_offset() -> list[dict]:
    # Offset is the gap between a target's AC and the attacker's total bonus.
    return [
        {"offset": offset, "hit": round(combat.hit_probability(0, offset), 4)}
        for offset in range(12, 29)
    ]


def damage() -> list[dict]:
    return [
        {
            "energy": e,
            "d10": combat.average_damage(e, 10),
            "d8": combat.average_damage(e, 8),
            "d6": combat.average_damage(e, 6),
        }
        for e in range(1, 7)
    ]


def rounds() -> list[dict]:
    return [
        {
            "energy": e,
            "normal": combat.rounds_to_kill(SAMPLE_HP, e, 10, 1.0),
            "resisted": combat.rounds_to_kill(SAMPLE_HP, e, 10, 0.5),
            "vulnerable": combat.rounds_to_kill(SAMPLE_HP, e, 10, 2.0),
        }
        for e in range(1, 7)
    ]


def main() -> None:
    hbo, dmg, rnd = hit_by_offset(), damage(), rounds()

    _write_json(DATA / "hit-by-offset.json", hbo)
    _write_json(DATA / "damage.json", dmg)
    _write_json(DATA / "rounds-to-kill.json", {"sample_hp": SAMPLE_HP, "rows": rnd})
    _write_json(
        DATA / "aoe-breakeven.json",
        {"single_die": 10, "area_die": 6, "targets": combat.aoe_breakeven()},
    )

    _write_md(
        DATA / "hit-by-offset.md",
        "Hit chance by the gap between a target's AC and the attacker's total bonus.",
        ["AC minus bonus", "Hit"],
        [[r["offset"], _pct(r["hit"])] for r in hbo],
    )
    _write_md(
        DATA / "damage.md",
        "Average damage by Energy spent and die size (the die steps down for area, range, or "
        "duration).",
        ["Energy", "d10", "d8", "d6"],
        [[r["energy"], r["d10"], r["d8"], r["d6"]] for r in dmg],
    )
    _write_md(
        DATA / "rounds-to-kill.md",
        f"Rounds to drop a {SAMPLE_HP} HP target by Energy spent (placeholder HP until the "
        "Attunement curve exists).",
        ["Energy", "Normal", "Resisted", "Vulnerable"],
        [[r["energy"], r["normal"], r["resisted"], r["vulnerable"]] for r in rnd],
    )


if __name__ == "__main__":
    main()
